- name: "Playbook para execucao de tarefas"
  hosts: servidores
  gather_facts: true
  remote_user: root
  
  tasks:
    - name: "Teste de Ping"
      ping:

    - name: "Instalando Apache"
      apt:
        name: apache2
        state: latest
        install_recommends: yes
        update_cache: yes
    
    - name: "Inicializando Apache"
      service: 
        name: httpd
        state: started
        enabled: yes
      
    # - name: "Inicializando Apache - Collection"
    #   ansible.bultin.service:
    #     name: httpd
    #     state: started
    #     enabled: yes

    - name: "Configurando Pagina Inicial"
      ansible.builtin.template:
        src: index.html
        dest: /var/www/html/index.html

    # - name: "Configurando Pagina Inicial"
    #   template:
    #     src: index.html
    #     dest: /var/www/html/index.html