---
# tasks file for volume-add
- name: "Adicionando novo disco"
  amazon.aws.ec2_vol:
    instance: "i-0ec16b4ca74fab91e"
    delete_on_termination: yes
    device_name: /dev/sdf
    volume_type: gp3
    volume_size: 20
    iops: 250
    region: "us-east-2"