---
# tasks file for volume-add
- name: "Adicionando novo disco"
  amazon.aws.ec2_vol:
    instance: "i-09a907464c7dd76af"
    delete_on_termination: yes
    device_name: /dev/sdf
    volume_type: gp3
    volume_size: 20
    iops: 250
    region: "us-east-2"