---
# tasks file for tech-hack-role

    - name: "Teste de Ping"
      ping:

    - name: "Instalando {{ pacotes }}"
      apt:
        name: "{{ pacotes }}"
        state: latest
        install_recommends: yes
        update_cache: yes
      notify: "Inicializando Apache"
      
    # - name: "Inicializando Apache - Collection"
    #   ansible.bultin.service:
    #     name: apache2
    #     state: started
    #     enabled: yes

    - name: "Configurando Pagina Inicial"
      ansible.builtin.template:
        src: index.html
        dest: /var/www/html/index.html

    # - name: "Configurando Pagina Inicial"
    #   template:
    #     src: index.html
    #     dest: /var/www/html/index.html